CREATE TABLE `PERSON` (
  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(30) NOT NULL,
  `SURNAME` VARCHAR(30) NOT NULL,
  `ADDITIONAL_INFO`  VARCHAR(70),
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;